name: aws_transcribe_streaming
description: "AWS Transcribe Streaming client for producing real-time transcriptions for your media content using HTTP/2."
version: 0.1.0
homepage: https://github.com/javer/aws_transcribe_streaming
repository: https://github.com/javer/aws_transcribe_streaming

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.0.0
  aws_common: ^0.6.0
  aws_signature_v4: ^0.5.0
  convert: ^3.0.0
  crypto: ^3.0.0
  http2: ^2.1.0
  uuid: ^3.0.0

dev_dependencies:
  lints: ^3.0.0

topics:
  - aws
  - transcribe
  - streaming
  - client
  - audio
